pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:latest
    action: EnsureCluster

  test:
    image: maven:3.5-jdk-11-slim
    commands:
    - mvn clean test

  build_container:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: '{{ .DRONE_REPO }}'
    tags: '{{ trunc 7 .DRONE_COMMIT_SHA }}'
    log: debug

  package_application:
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
    - helm package -u ./.banzaicloud/charts/spotguide-java-vault

  deploy_application:
    image: banzaicloud/ci-pipeline-client:latest
    action: EnsureDeployment
    deployment:
      name: './spotguide-java-vault-1.0.0.tgz'
      reuseValues: true
      releaseName: '{{ .DRONE_REPO_NAME }}'
      values:
        deployment:
          image:
            repository: '{{ .DRONE_REPO }}'
            tag: '{{ trunc 7 .DRONE_COMMIT_SHA }}'
            pullPolicy: Always
        ingress:
          hosts:
          - "app.{{ .DRONE_REPO_NAME }}.{{ .CLUSTER_NAME }}.{{ .ORG_NAME }}.banzaicloud.io"
